// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace WinFormsApp1.Models;

public partial class Partner
{
    public int Id { get; set; }

    [Required(ErrorMessage ="Тип партнера обязателен для заполнения")]
    public int PartnerTypeId { get; set; }

    [Required(ErrorMessage = "Наименование партнера обязательно для заполнения")]
    [MaxLength(100)]
    public string Name { get; set; }

    [Required(ErrorMessage = "ФИО директора обязательно для заполнения")]
    public string Director { get; set; }

    [Required(ErrorMessage ="Email обязателен для заполнения")]
    [EmailAddress(ErrorMessage ="Некорректный email")]
    public string Email { get; set; }

    [Required(ErrorMessage = "Номер телефона обязателен для заполнения")]
    [MaxLength(16)]
    [MinLength(13)]
    public string Phone { get; set; }

    [Required(ErrorMessage = "Адрес обязателен для заполнения")]
    public string Address { get; set; }

    public double? Inn { get; set; }

    [Required(ErrorMessage = "Рейтинг обязателен для заполнения")]
    [Range(1,10, ErrorMessage ="Рейтинг должен быть целым числом от 1 до 10")]
    public int Rating { get; set; }

    public virtual ICollection<PartnerProduct> PartnerProducts { get; set; } = new List<PartnerProduct>();

    public virtual PartnerType PartnerType { get; set; }
}