// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WinFormsApp1.Models;

public partial class PartnerProduct
{
    public int Id { get; set; }

    public int ProductId { get; set; }

    public int PartnerId { get; set; }

    public long Count { get; set; }

    public DateTime? SaleDate { get; set; }

    public virtual Partner Product { get; set; }

    public virtual Product ProductNavigation { get; set; }
}