// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WinFormsApp1.Models;

public partial class PartnerType
{
    public int Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Partner> Partners { get; set; } = new List<Partner>();
}