// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WinFormsApp1.Models;

public partial class ProductType
{
    public int Id { get; set; }

    public string Name { get; set; }

    public double ProductTypeRate { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}