// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WinFormsApp3.Models;

public partial class MaterialType
{
    public int Id { get; set; }

    public string Name { get; set; }

    public double DefectiveRate { get; set; }

    public virtual ICollection<ProductMaterialType> ProductMaterialTypes { get; set; } = new List<ProductMaterialType>();
}