// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WinFormsApp3.Models;

public partial class Partner
{
    public int Id { get; set; }

    public int PartnerTypeId { get; set; }

    public string Name { get; set; }

    public string Director { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string Address { get; set; }

    public string Inn { get; set; }

    public int Rating { get; set; }

    public virtual PartnerType PartnerType { get; set; }

    public virtual ICollection<Sale> Sales { get; set; } = new List<Sale>();
}