// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WinFormsApp3.Models;

public partial class Product
{
    public int Id { get; set; }

    public int? ProductTypeId { get; set; }

    public string НаименованиеПродукции { get; set; }

    public double? Article { get; set; }

    public double? MinCost { get; set; }

    public virtual ICollection<ProductMaterialType> ProductMaterialTypes { get; set; } = new List<ProductMaterialType>();

    public virtual ProductType ProductType { get; set; }

    public virtual ICollection<Sale> Sales { get; set; } = new List<Sale>();
}