// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WinFormsApp3.Models;

public partial class Sale
{
    public int Id { get; set; }

    public int? ProductId { get; set; }

    public int? PartnerId { get; set; }

    public long Count { get; set; }

    public DateTime? SalesDate { get; set; }

    public virtual Partner Partner { get; set; }

    public virtual Product Product { get; set; }
}